application: syllabus-wizard
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: "7d"

- url: /static
  static_dir: _static
  expiration: "1d"

- url: /admin.*
  script: main.app
  secure: always

- url: /manage.*
  script: main.app
  secure: always

- url: /login.*
  script: main.app
  secure: always

- url: /logout.*
  script: main.app
  secure: always

- url: /.*
  script: main.app
  secure: never

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest